config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_post, only: [:create, :edit, :update, :destroy]
	before_action :find_comment, only: [:edit, :update, :destroy]

	def create
		@comment = @post.comments.build(comment_params)
		@comment.user_id = current_user.id
		@comment.save

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		
		if @comment.update(comment_params)
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to post_path(@post)
	end

	private

	def comment_params
		params.require(:comment).permit(:comment)
	end

	def find_post
		@post = Post.find(params[:post_id])
	end

	def find_comment
		@comment = @post.comments.find(params[:id])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order("created_at DESC")
	end

	def show
		
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content)
	end

	def find_post
		@post = Post.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
	.content
		%p.comment_content= comment.comment
		%p.comment_author
			by
			= comment.user.email
			= time_ago_in_words(comment.created_at)
			ago

	.buttons
		- if user_signed_in? && comment.user_id == current_user.id
			= link_to "Edit", edit_post_comment_path(comment.post, comment)
			= link_to "Delete", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?"}

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
	= f.input :comment
	= f.submit

app/views/comments/edit.html.haml
%h1 Edit Reply

= simple_form_for([@post, @comment]) do |f|
	= f.input :comment
	= f.submit

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Teichner's Rails Forum
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	%link{ rel: "stylesheet", href: "http://fonts.googleapis.com/css?family=Lato:300,400,700", type: "text/css"}
	%link{:rel => "stylesheet", :href => "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}/
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%header.main_header.clearfix
		.wrapper
			#logo
				%p= link_to "Teichner's Rails Forum", root_path
			#buttons
				- if user_signed_in?
					= link_to "New Post", new_post_path
					= link_to "Sign Out", destroy_user_session_path, method: :delete
				- else
					= link_to "Sign Up", new_user_registration_path
					= link_to "Sign In", new_user_session_path

	.wrapper
		%p.notice= notice
		%p.alert= alert

	.wrapper
		= yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
	= f.input :title
	= f.input :content
	= f.submit

app/views/posts/edit.html.haml
%h1 Edit Post

= render 'form'

= link_to "Cancel", post_path

app/views/posts/index.html.haml
#posts
	- @posts.each do |post|
		.post
			%h2= link_to post.title, post
			%p.date
				Published
				= time_ago_in_words(post.created_at)
				ago by
				= post.user.email

app/views/posts/new.html.haml
%h1 New Post

= render 'form'

app/views/posts/show.html.haml
#post_content
	%h1= @post.title
	%p= @post.content

	#comments
		%h2
			= @post.comments.count
			Comments
		= render @post.comments

		- if user_signed_in?
			%h3 Reply to thread
			= render 'comments/form'
		- else
			%h3.main_header.clearfix
				#buttons_left
					= link_to "Sign in to reply", new_user_session_path

	- if user_signed_in? && @post.user_id == current_user.id
	
		%br
		%hr
		%br

		= link_to "Edit", edit_post_path(@post), class: "button"
		= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?"}, class: "button"